let userName = prompt("Привет user! Как тебя зовут?")
alert("Приятно познакомиться, " + userName)
let userMood = prompt("Как дела " + userName)
alert("Прикольно")
let userOld = prompt("Сколько тебе лет?")
alert("Ого ты уже взрослый")
let userDela = prompt( userName + " а чем ты увлекаешся")
alert("Круто! А я учу JavaScript " )
let userMusic = prompt("Какой твой любимый жанр музыки?")
alert("Вау! А мой K-pop")
let userFilm = prompt("Какой твой любимый фильм")
alert("Не знаю такой, надо будет посмотреть")
let userGame = prompt("Какая твоя любимая игра?")
alert("О! Это тоже моя любимая игра ")
let userSchool = prompt("А где ты учишся?")
alert("А я учусь в K.Fund school")
let userMarks = prompt("Хорошо учишся?")
alert("Молодец!")
let userSport = prompt("Занимаешся спортом?")
alert("В здоровом теле, здоровий дух")
alert("Если ты долистал до этого момента, ты должен мне шоколадку :)")